### ISSUE TITLE
Create a Repo.txt

### ISSUE THREAD

**Issue by abidiskou** [dzcode-io/Learn-Git-and-Github#2]
In this file you will learn what is a repositories and how it work with 
The commit 
Push and pull request 
Merge
Forks and more about basics in git & github

**Comment by SofianeHamlaoui** [comment]
Yes, we will use this to teach handling Git, Github and it's repositories.

**Comment by ZibanPirate** [comment]
@abidiskou, thanks for opening the issue, please check the [slack workspace](https://dzcode.slack.com/) for all of your questions.

**Comment by abidiskou** [comment]
@ZibanPirate thank you so much

**Comment by SofianeHamlaoui** [comment]
Perfect, I’ll close the issue.
